# --- DATA 15 SOAL PILIHAN GANDA ---
SOAL_UJIAN = [
    {"no": 1, "tanya": "Apa ekstensi file standar untuk skrip Python?", "opsi": ["A. .pt", "B. .py", "C. .pyt", "D. .txt"], "kunci": "B. .py"},
    {"no": 2, "tanya": "Simbol apa yang digunakan untuk menulis komentar satu baris di Python?", "opsi": ["A. //", "B. /*", "C. #", "D. --"], "kunci": "C. #"},
    {"no": 3, "tanya": "Fungsi bawaan apa yang digunakan untuk mengetahui jumlah elemen dari sebuah list?", "opsi": ["A. size()", "B. length()", "C. len()", "D. count()"], "kunci": "C. len()"},
    {"no": 4, "tanya": "Manakah dari tipe data berikut yang bersifat immutable di Python?", "opsi": ["A. List", "B. Dictionary", "C. Set", "D. Tuple"], "kunci": "D. Tuple"},
    {"no": 5, "tanya": "Bagaimana cara mendefinisikan sebuah fungsi di Python?", "opsi": ["A. function myFunction():", "B. def myFunction():", "C. create myFunction():", "D. func myFunction():"], "kunci": "B. def myFunction():"},
    {"no": 6, "tanya": "Apa output dari fungsi print(type([]))?", "opsi": ["A. <class 'list'>", "B. <class 'array'>", "C. <class 'dict'>", "D. <class 'tuple'>"], "kunci": "A. <class 'list'>"},
    {"no": 7, "tanya": "Keyword apa yang digunakan untuk perulangan selama kondisi bernilai True?", "opsi": ["A. for", "B. foreach", "C. while", "D. loop"], "kunci": "C. while"},
    {"no": 8, "tanya": "Method untuk menambahkan elemen baru ke urutan paling belakang dari list adalah?", "opsi": ["A. insert()", "B. add()", "C. append()", "D. push()"], "kunci": "C. append()"},
    {"no": 9, "tanya": "Berapa hasil dari operasi matematika 2 ** 3 di Python?", "opsi": ["A. 5", "B. 6", "C. 8", "D. 9"], "kunci": "C. 8"},
    {"no": 10, "tanya": "Statement untuk menghentikan dan keluar dari loop secara paksa adalah?", "opsi": ["A. stop", "B. exit", "C. break", "D. continue"], "kunci": "C. break"},
    {"no": 11, "tanya": "Bagaimana cara mengimpor modul bawaan os di Python?", "opsi": ["A. include os", "B. import os", "C. using os", "D. require os"], "kunci": "B. import os"},
    {"no": 12, "tanya": "Manakah penamaan variabel yang benar di Python?", "opsi": ["A. 1variable = 'x'", "B. my-variable = 'x'", "C. my_variable = 'x'", "D. var x = 'x'"], "kunci": "C. my_variable = 'x'"},
    {"no": 13, "tanya": "Apa fungsi dari perintah input()?", "opsi": ["A. Menampilkan teks", "B. Membaca masukan pengguna", "C. Mengimpor file", "D. Menghapus memori"], "kunci": "B. Membaca masukan pengguna"},
    {"no": 14, "tanya": "Tipe data dari nilai True atau False disebut dengan?", "opsi": ["A. String", "B. Integer", "C. Boolean", "D. Float"], "kunci": "C. Boolean"},
    {"no": 15, "tanya": "Apa hasil dari operasi 10 // 3 di Python?", "opsi": ["A. 3.33", "B. 3", "C. 1", "D. 0"], "kunci": "B. 3"}
]